### ISSUE TITLE
code.dlang.org broken

### ISSUE THREAD

**Issue by Zaramzan** [D-Programming-Language/dub-registry#47] opened 2014-03-03 13:54 UTC
Stranges with this site.

http://code.dlang.org/download - 500 error code
```
500 - Internal Server Error

Internal Server Error

Internal error information:
std.file.FileException@std/file.d(2394): public/files: Too many open files
----------------
./dub-registry(bool std.file.DirIteratorImpl.stepIn(immutable(char)[])+0x61) [0xac17f1]
./dub-registry(ref std.file.DirIteratorImpl std.file.DirIteratorImpl.__ctor(immutable(char)[], std.file.SpanMode, bool)+0x9d) [0xac1b0d]
./dub-registry(std.file.DirIteratorImpl* std.conv.emplace!(std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplace(std.file.DirIteratorImpl*, ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x48) [0xabf70c]
./dub-registry(void std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted.RefCountedStore.initialize!(immutable(char)[], std.file.SpanMode, bool).initialize(ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x83) [0xaaaa37]
./dub-registry(ref std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted.__ctor!(immutable(char)[], std.file.SpanMode, bool).__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x11) [0xaaa9a9]
./dub-registry(ref std.file.DirIterator std.file.DirIterator.__ctor(immutable(char)[], std.file.SpanMode, bool)+0x40) [0xa95f90]
./dub-registry(std.file.dirEntries.FilterResult!(_D3std4file10dirEntries1fMFS3std4file8DirEntryZb, std.file.DirIterator).FilterResult std.file.dirEntries(immutable(char)[], immutable(char)[], std.file.SpanMode, bool)+0x77) [0xa9646b]
./dub-registry(void dubregistry.web.DubRegistryWebFrontend.showDownloads(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x537) [0x7b350b]
./dub-registry(void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x179) [0x7cc44d]
./dub-registry(bool vibe.http.server.handleRequest(vibe.core.stream.Stream, vibe.core.net.TCPConnection, vibe.http.server.HTTPServerListener, ref vibe.http.server.HTTPServerSettings, ref bool)+0x17da) [0x7c150e]
./dub-registry(void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerListener)+0x12b) [0x7bfc47]
./dub-registry(void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings, void delegate(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)).void doListen(vibe.http.server.HTTPServerSettings, vibe.http.server.HTTPServerListener, immutable(char)[]).void __lambda60(vibe.core.net.TCPConnection)+0x2c) [0x7bbeb8]
./dub-registry(extern (C) nothrow void vibe.core.drivers.libevent2_tcp.onConnect(int, short, void*).void ClientTask.execute()+0x2d6) [0x7da80a]
./dub-registry(_D4vibe4core4core12__T7runTaskZ7runTaskFDFZvZS4vibe4core4task4Task12callDelegateFC4vibe4core4core8CoreTaskZv+0x2b) [0x7f2bdf]
./dub-registry(void vibe.core.core.CoreTask.run()+0x14a) [0x7eecce]
./dub-registry(void core.thread.Fiber.run()+0x2a) [0xab4f6e]
./dub-registry(fiber_entryPoint+0x61) [0xab4e79]
[(nil)]
```

**Comment by s-ludwig** [comment] 2015-04-16 19:54
Since this hasn't happened for months now, I expect this to be fixed by now. I'll keep the vibe.d issue open to remember to verify it using a benchmark tool, but it will be hard to reproduce it for the registry.

**Closed by s-ludwig** 2015-04-16 19:54 UTC
